---
title: "Beta Regression"
author: "Marcus Chery and Keiron Green"
date: '`r Sys.Date()`'

format: 
  html:
    code-fold: true
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

## Introduction

Beta regression is a statistical methodology tailored to address the
challenges associated with modeling continuous bounded response
variables, often constrained within the open interval (0, 1). Beta
regression, as introduced by [@ferrari2004] in their seminal paper,
offers an elegant framework for modeling proportions and percentages
with an emphasis on interpretability of model parameters. This
foundational work serves as a cornerstone for subsequent research and
applications.

This report delves into the application of beta regression within the
context of heart disease data analysis. Our objective is to provide a
thorough understanding of beta regression, its practical implementation
using the "betareg" package in R, and its real-world relevance through
heart disease data. Throughout the report, we offer practical examples,
code snippets, and graphs to facilitate hands-on learning. Additionally,
we address the limitations of beta regression and discuss potential
future research directions. The goal of this report is to equip readers
with the knowledge and skills needed to effectively utilize beta
regression in heart disease analysis, while also fostering awareness of
its boundaries and avenues for further exploration.

In beta regression, the dependent variable is assumed to follow a beta
distribution, and the goal is to model its relationship with one or more
independent variables. Beta regression is suitable for data where the
response variable lies within a closed interval, such as proportions,
percentages, or rates. It considers both the mean and the dispersion of
the data [@ferrari2004] .

The beta distribution is characterized by two parameters: alpha (α) and
beta (β). These parameters can be modeled as a function of predictor
variables, allowing for the analysis of how independent variables
influence the shape of the distribution.

Like logistic regression, beta regression often uses a link function to
relate the mean of the beta distribution to the linear combination of
predictor variables. Common link functions include logit, probit, and
log-log. The coefficients obtained from beta regression provide insights
into how changes in the predictor variables affect the distribution of
the response variable, including its mean and variability.

Complementing this, the "betareg" package for R, as presented by
[@cri2010], provides various methods and procedures for implementing
beta regression models in R. Building on the foundation laid by
[@ferrari2004], [@cri2010] introduce the "betareg" package for R,
offering a practical implementation of beta regression models. This
paper is instrumental in bringing beta regression into the realm of data
analysis and showcases the package's utility in addressing challenges
related to continuous bounded response variables.

[@guolo2014] seek to expand on beta regression. The authors incorporate
a Gaussian copula to model serial dependence in the data, making it
applicable to time series analysis. The study's practical application
involves analyzing influenza-like-illness incidence data from the Google
Flu Trends project. Their methodology provides a framework for analyzing
bounded time series data and offers insights into inference, prediction,
and control in this context.

Moreover, the paper authored by [@espinheira2008] unveils innovative
residuals, based on Fisher's scoring iterative algorithm, enhancing
model assessments and bias correction---a pivotal contribution to the
methodology's practical applicability. They address a common challenge
in statistical analysis by offering a practical solution for improved
model assessments and bias correction. The study presents new residuals
based on Fisher's scoring iterative algorithm, demonstrating their
superiority in various scenarios, particularly in small sample sizes.

Various papers throughout the years have sought to improve the basic
beta regression techniques of [@ferrari2004]. [@simas2010] delve into
bias correction methods for beta regression models in the quest for
improved estimators in beta regression. They address biases in parameter
estimation, a critical concern. Recognizing the potential for bias in
parameter estimation, especially in small sample sizes, the paper
provides closed-form expressions for second-order biases in maximum
likelihood estimators. The authors present various methods for bias
correction, including analytical approaches and bootstrap bias
adjustment, enhancing the accuracy of model assessments and mitigating
erroneous conclusions.

Likewise, [@schmid2013] introduced one such enhancement known as the
"boosted beta regression" as a novel extension of classical beta
regression. [@schmid2013] address complex modeling scenarios with many
predictor variables, multicollinearity, nonlinear relationships, and
overdispersion dependencies. They utilize the gamboostLSS algorithm to
efficiently estimate beta regression models, making it possible to fit
models while preserving the structure of beta regression. The method's
effectiveness is demonstrated through ecological data applications,
highlighting its advantages in terms of model fit and prediction
accuracy.

[@abonazel2022] took a different approach. They focused on improving the
estimation of beta regression models when multicollinearity was present
among regressors. They introduced the Dawoud--Kibria estimator as an
alternative to the conventional maximum likelihood estimator (BML) when
dealing with such situations. The authors derived the properties of this
new estimator and assess its performance through theoretical
comparisons, Monte Carlo simulations, and a real-life application.

Finally, it is important to note the challenges of beta regression.
[@douma2019] addresses one challenge of analyzing proportional data in
ecology and evolution. Proportional data, common in these fields, pose
unique statistical challenges due to their bounded nature and varying
variances. The paper introduces beta and Dirichlet regression techniques
as effective tools for analyzing such data. These methods allow for
analysis at the original scale, reducing bias and simplifying
interpretation. The article provides practical guidance on model fitting
and reporting.

[@couri2022] focuses on the computational challenges of estimating
parameters in beta regression models. The authors evaluate ten
algorithms for parameter estimation and find that four, including
simulated annealing, perform well. The paper also examines the optim
function in R and suggests its use in challenging cases. Simulated
annealing is recommended, particularly when the optim function fails.
Overall, the research offers insights into improving parameter
estimation for beta regression models in various applications.

Furthermore, one such limitation of classical beta regression is its
handling of zero or one inflated data. [@ospina2012] introduce a
versatile class of regression models, zero-or-one inflated beta
regression, specifically tailored to address datasets containing
continuous proportions with zeros or ones. The paper offers a flexible
solution for modeling mixed continuous-discrete distributions, essential
in real-world scenarios such as income contributions or work-related
activities. By combining the beta distribution with a degenerate
distribution at zero or one, the authors provide a robust framework for
effective modeling, parameter estimation, diagnostics, and model
selection.

## Methods

## Analysis and Results

### Data and Visualization

### Statistical Modeling

### Conclusion

## References
